# Generated by Django 3.0.8 on 2020-07-30 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_amount', models.FloatField()),
                ('currency', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiration_month', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('status', models.CharField(max_length=12)),
                ('authcode', models.IntegerField()),
                ('txn_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
