# Generated by Django 3.0.8 on 2020-07-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpayhistory',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='razorpayhistory',
            name='expiration_month',
        ),
    ]
