# Generated by Django 3.0.8 on 2020-08-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayapp', '0005_remove_razorpayhistory_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayhistory',
            name='txn_amount',
            field=models.IntegerField(),
        ),
    ]
