# Generated by Django 3.0.8 on 2020-08-01 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayapp', '0006_auto_20200801_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayhistory',
            name='txn_date',
            field=models.IntegerField(default=django.utils.timezone.now),
        ),
    ]
